### ISSUE TITLE
Device Flags

### ISSUE THREAD

**Issue by garysharp** [garysharp/Disco#138]
As with User Flags, it has been requested that Device Flags be made available with the same functionality.

**Comment by ShadowPeo** [comment]
Specifically with this we are looking at being able to flag insurance having been used on the device so that when a device is assigned from Person A to Person B, we know the insurance has already been used so we can ideally allocate a different device or know we need to absorb the cost somewhere if an insurance claim needs to be made on the new user

**Comment by garysharp** [comment]
Works completed
