### ISSUE TITLE
Not Syncing Device/User Groups on Join

### ISSUE THREAD

**Issue by mickyvx** [garysharp/Disco#78]
Disco isn't automatically synchronizing devices with their attached user/device AD groups. Have to manually go into the device profile and choose to sync.

Using the latest Disco Bootstrap client.

**Comment by mickyvx** [comment]
This is still an issue for me. Have to manually synchronize device profiles for them to get added into correct device security groups.

**Comment by garysharp** [comment]
The error report provided is linked to the *Network Logon Dates* update task which fires when a device is accessed with the Disco web interface:
![disco - device last seen](https://cloud.githubusercontent.com/assets/1687386/6013220/c51dbf3a-aba5-11e4-8075-088a006189b5.png)
This error indicates an issue caused by network interruption, faulty network hardware or packet/port filtering. While it may indicate some network instability this error doesn't directly relate to the Synced Groups.

Managed Groups delay their changes to AD by about 10-20 seconds (batching changes together). AD may also take a few moments to synchronise changes among controllers.

Are you able to consistently replicate the issue or does it fail occasionally? Can you see any pattern in when it fails? Can you provide repo steps?

**Comment by mickyvx** [comment]
Sorry Gary for late response. I have been monitoring it and some times it will take 10 - 20 minutes for it to sync properly in AD, so I have to manually sync the groups when we notice a laptop can't access wireless because their laptop isn't synced to the wireless access group.
